# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCemera.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(815, 545)
        self.label_Show_Image = QtWidgets.QLabel(Dialog)
        self.label_Show_Image.setGeometry(QtCore.QRect(48, 120, 471, 321))
        self.label_Show_Image.setObjectName("label_Show_Image")
        self.btn_Click_Exit = QtWidgets.QPushButton(Dialog)
        self.btn_Click_Exit.setGeometry(QtCore.QRect(630, 350, 80, 23))
        self.btn_Click_Exit.setObjectName("btn_Click_Exit")
        self.btn_Click_Run = QtWidgets.QPushButton(Dialog)
        self.btn_Click_Run.setGeometry(QtCore.QRect(630, 280, 80, 23))
        self.btn_Click_Run.setObjectName("btn_Click_Run")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_Show_Image.setText(_translate("Dialog", "TextLabel"))
        self.btn_Click_Exit.setText(_translate("Dialog", "EXIT"))
        self.btn_Click_Run.setText(_translate("Dialog", "RUN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
