# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_RUN.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_RUN(object):

    def setupUi_RUN(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.are_camera = QtWidgets.QScrollArea(self.centralwidget)
        self.are_camera.setGeometry(QtCore.QRect(0, 140, 781, 731))
        self.are_camera.setWidgetResizable(True)
        self.are_camera.setObjectName("are_camera")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 729))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.are_camera.setWidget(self.scrollAreaWidgetContents)
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(920, 800, 121, 61))
        self.btn_run.setObjectName("btn_run")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(790, 800, 121, 61))
        self.btn_stop.setObjectName("btn_stop")

        self.btn_go_to_mode_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_go_to_mode_set.setGeometry(QtCore.QRect(780, 0, 121, 61))
        self.btn_go_to_mode_set.setObjectName("btn_go_to_mode_set")


        self.label_OK_NG = QtWidgets.QLabel(self.centralwidget)
        self.label_OK_NG.setGeometry(QtCore.QRect(910, 0, 131, 61))
        self.label_OK_NG.setScaledContents(False)
        self.label_OK_NG.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OK_NG.setObjectName("label_OK_NG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_run.setText(_translate("MainWindow", "RUN"))
        self.btn_stop.setText(_translate("MainWindow", "STOP"))
        self.btn_go_to_mode_set.setText(_translate("MainWindow", "GO TO MODE SET"))
        self.label_OK_NG.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#00ff00;\">OK</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_RUN()
    ui.setupUi_RUN(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
